//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okargo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class paketler
    {
        public int gonderiID { get; set; }
        public string gonderi_no { get; set; }
        public string tc { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<int> nereden { get; set; }
        public Nullable<int> nereye { get; set; }
        public string adres { get; set; }
        public string nerede { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> agirlik { get; set; }
        public string aliciadisoyadi { get; set; }
        public Nullable<System.DateTime> tahminiteslim { get; set; }
        public Nullable<System.DateTime> alimsaati { get; set; }
        public Nullable<bool> dagitimacikti { get; set; }
    
        public virtual sehirler sehirler { get; set; }
        public virtual sehirler sehirler1 { get; set; }
    }
}
