//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okargo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int ID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> yetki { get; set; }
    }
}
