//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace havuzum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiyat
    {
        public int Fiyat1 { get; set; }
        public Nullable<int> Ogrenci { get; set; }
        public Nullable<int> Sivil { get; set; }
        public Nullable<int> AylıkOgrenci { get; set; }
        public Nullable<int> AylıkSivil { get; set; }
        public Nullable<int> HaftalıkOgrenci { get; set; }
        public Nullable<int> HaftalıkSivil { get; set; }
    }
}
