//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace havuzum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int RezervasyonId { get; set; }
        public Nullable<int> gunID { get; set; }
        public Nullable<int> saatID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tc { get; set; }
        public Nullable<int> cinsID { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<int> durumID { get; set; }
    }
}
