//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcsaha.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gunler
    {
        public int gunID { get; set; }
        public string gun { get; set; }
    }
}
