//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcsaha.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hcsahaEntities : DbContext
    {
        public hcsahaEntities()
            : base("name=hcsahaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<gunler> gunler { get; set; }
        public virtual DbSet<resimler> resimler { get; set; }
        public virtual DbSet<rezervasyon> rezervasyon { get; set; }
        public virtual DbSet<saatler> saatler { get; set; }
        public virtual DbSet<siteYazilari> siteYazilari { get; set; }
    }
}
