//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcsaha.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervasyon
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> gun { get; set; }
        public Nullable<int> saat { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tel { get; set; }
        public Nullable<bool> onay { get; set; }
    }
}
