//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hcsaha.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class siteYazilari
    {
        public int yaziID { get; set; }
        public string baslik { get; set; }
        public string yazi { get; set; }
        public string tel { get; set; }
        public string mail { get; set; }
        public string iletisimBaslik { get; set; }
        public string iletisimYazi { get; set; }
        public string rezervasyonbaslik { get; set; }
        public string rezervasyonyazi { get; set; }
        [AllowHtml]
        public string hakkimizda { get; set; }
        public string header { get; set; }
    }
}
